### ISSUE TITLE
Make me less lonely when I look at the nav

### ISSUE THREAD

**Issue by darrellsilver** [Thinkful/ui#107]
This outlined person is so lonely! Why's (s)he there?

![screen shot 2015-06-29 at 2 22 30 pm](https://cloud.githubusercontent.com/assets/24387/8416754/cd07a358-1e75-11e5-8876-d775ab096340.png)

**Comment by darrellsilver** [comment]
@paulaborowska what's the right design here?

**Comment by paulaborowska** [comment]
What in the world....?

A navigation should not a social situation. I don't think we need to add icons to these, these are secondary links. And this user icon is used for something else. If you want to rethink navigation ui make it a trello card for clean up, GitHub is not a place for design suggestions like this.

**Comment by darrellsilver** [comment]
misunderstanding about what this issue is all about... that icon is _already_ there. This issue is about removing it. Reopening.

**Comment by paulaborowska** [comment]
Haha yes, please get rid of that icon, it should not be there 0.o 
(The correct design is no icon in the drop down.)
