### ISSUE TITLE
[navbar] Nothing happens when I click the logo

### ISSUE THREAD

**Issue by diezguerra** [Thinkful/ui#108]
How come clicking the logo (MastHead) doesn't take you home?

/cc @jcudmore @evanrs

**Comment by jcudmore** [comment]
Agree - should go "home" which means:

TFL - dashboard.thinkful.com/library
Core - dashboard.thinkful.com

TFL will eventually have a "home" / dashboard, but until then this works ^

**Comment by evanrs** [comment]
In our prior conversations @jcudmore @paulaborowska and myself chose to emulate Twitters navbar. Take a look and you'll see the bird does nothing.

**Comment by diezguerra** [comment]
Fair, but.

Take a look at any other website with a logo on it and you will find that it is clickable and it will take you home. It's a UI meme as old as the web itself. People are expecting that behavior.

Old ideas for old people? Nein. Open snapchat and tap on the ghost? You get your profile. Facebook? Your wall. Instagram web? Your feed. Medium? Your feed.

**Comment by jcudmore** [comment]
The Twitter T does do something! Scroll down in your timeline a bit and click the T to jump back to the top / "home".

**Comment by paulaborowska** [comment]
I second Saul, better to keep the convention going. I actually thought it did take you to home up until a different discussion an hour ago.

**Comment by jcudmore** [comment]
Ok so as discussed: T can go "home" / dashboard.thinkful.com. For TFL that would be dashboard.thinkful.com/library

**Comment by diezguerra** [comment]
Seems this is fixed but the URL doesn't point to the user's "home" link

**Comment by evanrs** [comment]
There has been plenty of IRL conversations and it looks like the last place we left off was that it went to www. @benjaminwhite and @darrellsilver should be able to clarify.

**Comment by darrellsilver** [comment]
It should go to the user's home screen... just like the "Home" button:

<img width="807" alt="screen shot 2015-07-29 at 1 31 52 pm" src="https://cloud.githubusercontent.com/assets/24387/8964961/8b85ab12-35f6-11e5-8389-fc2a5104482b.png">

**Comment by paulaborowska** [comment]
@darrell, shouldn’t the just t function the same way as ‘home’? Is that what you’re trying to say with that image?


—
Paula

**Comment by darrellsilver** [comment]
yeah – exactly. the logo should be changed to go to the same place as the "Home" link.

**Comment by evanrs** [comment]
Hah, I believe this card solidly confirms where the T should go.

**Comment by evanrs** [comment]
@benjaminEwhite I took a moment to close this issue, since you were on this last could you review pr #130 ?
