### ISSUE TITLE
Underline in menu bar lacks clarity

### ISSUE THREAD

**Issue by jcudmore** [Thinkful/ui#109]
![screen shot 2015-07-01 at 1 37 30 pm](https://cloud.githubusercontent.com/assets/9043153/8460911/7741ff18-1ff6-11e5-879e-a221b90ddde6.png)

Does line mean I'm in Courses or slack? 

@paulaborowska should we have a different "active" state for items in the menu? underline works fine in the nav, but in menu it is not clear.

**Comment by paulaborowska** [comment]
Is it hard to see what this would look like if instead of the underline the background colour changed to a lighter gray?

**Comment by jcudmore** [comment]
@evanrs we can knock this one out together?

**Comment by paulaborowska** [comment]
If that doesn't look too great bold it instead. I would urge you not to do both at once though, it might be too much. 

I couldn't play around with this in browser bc the nav kept on disappearing so if you can send me screenshots that would be fantastic.

**Comment by tholex** [comment]
I think this got switched to just bold instead of outline recently, just needs to be deployed to Myna + Courses.
