### ISSUE TITLE
sometimes icons load all craaaazy

### ISSUE THREAD

**Issue by darrellsilver** [Thinkful/ui#14]
![screen shot 2015-05-22 at 7 10 07 am](https://cloud.githubusercontent.com/assets/24387/7769454/d5889970-0051-11e5-8b66-76aad337650b.png)

Kara saw it yesterday; I just saw it for the first time now... happened then went away upon reload

**Comment by evanrs** [comment]
This is a [tfstyleguide](https://github.com/Thinkful/tfstyleguide) issue, I've re-opened here: https://github.com/Thinkful/tfstyleguide/issues/20
