### ISSUE TITLE
Add active state for nav links

### ISSUE THREAD

**Issue by jcudmore** [Thinkful/ui#17]

**Comment by jcudmore** [comment]
@paulaborowska @tholex  thoughts?

**Comment by evanrs** [comment]
Will address at some point in the next week and a half. The AppBar is a little dumb ATM, it will see deeper tie ins with each app soon.

**Comment by evanrs** [comment]
Closed by https://github.com/Thinkful/tfcommons/commit/7227244db6235f3dcdc927ae890f9172b2dec1e1
