### ISSUE TITLE
Add "Take student" to drop down for admins

### ISSUE THREAD

**Issue by jcudmore** [Thinkful/ui#18]

**Comment by evanrs** [comment]
@jcudmore it already appears for mentors, can you clarify why it would appear for admins?
![screen shot 2015-05-26 at 2 40 24 pm](https://cloud.githubusercontent.com/assets/297455/7820243/33bcacbe-03b5-11e5-9648-7cf07eee4b74.png)

**Comment by jcudmore** [comment]
IMO admins should be able to access all apps. i asked around and varun uses take student pretty frequently.
