### ISSUE TITLE
Add "Workshops" to nav

### ISSUE THREAD

**Issue by jcudmore** [Thinkful/ui#182]
Between Courses and Mentors

**Comment by jcudmore** [comment]
cc: @darrellsilver @catherinetf let's get more people in here ?

**Comment by catherinetf** [comment]
Agreed.

**Comment by darrellsilver** [comment]
How about swapping in the "Courses" nav:

<img width="685" alt="screen shot 2015-09-15 at 2 16 15 pm" src="https://cloud.githubusercontent.com/assets/24387/9885657/5bd8bf92-5bb4-11e5-9ab6-fe490f553fa3.png">

**Comment by jcudmore** [comment]
If we want more people to flow through Workshops page - I think it should be it's own link. let's discuss irl

**Comment by tholex** [comment]
yeah so now there's two places to go - library & workshops?

**Comment by jcudmore** [comment]
So @tholex:

- Add Workshops between Courses and Mentors
- Change links in the nav to be workshops and go to open-sessions
