### ISSUE TITLE
Add Activity link to AppBar for admins

### ISSUE THREAD

**Issue by jcudmore** [Thinkful/ui#19]
Call it "My students". It should probably sit between home and office hours. 

@paulaborowska what icon did you want to use?

**Comment by paulaborowska** [comment]
“user"


—
Paula

**Comment by evanrs** [comment]
We have limited space in the navigation, `My ` is not a significant improvement over `Students` alone. If we're set on that title convention then we need to lower the font size.

**Comment by evanrs** [comment]
Also, it already appears for mentors, changing to `add for admins`

**Comment by evanrs** [comment]
![screen shot 2015-05-26 at 2 40 24 pm](https://cloud.githubusercontent.com/assets/297455/7820264/527649da-03b5-11e5-845f-c126d0597c48.png)

**Comment by jcudmore** [comment]
@tholex if we increase the width when the nav switches to mobile view, could we then fit "My students"?

**Comment by tholex** [comment]
My Students should just fit in the right hand side

**Comment by jcudmore** [comment]
@tholex if we now have Home/Library, does My Students fit? Right side is fine too.

**Comment by tholex** [comment]
For mentors:
Let's move Office Hours into the dropdown, and add this "My Students" link on the left.
