### ISSUE TITLE
Add Slack to dropdown for everyone

### ISSUE THREAD

**Issue by jcudmore** [Thinkful/ui#20]
With library replacing current view of Dashboard, we are losing the slack module. This seems like a logical place.  It can link to general-discussion. thoughts?

**Comment by evanrs** [comment]
At the moment it may take some time to get slack working across our sites, the client code is clear, but we have to verify that cross site requests are working with auth and decide where the slack backend should really live. @diezguerra can you chime in / help set for priority?

**Comment by diezguerra** [comment]
Figuring out the cross site request stuff is probably worth it. Justin, where would the slack module be shown, if not in dashboard? Or do you want it in here just to park it?

/cc @jcudmore

**Comment by jcudmore** [comment]
@diezguerra the Library view is taking over dashboard, so there will no more slack module (the message box that Thomas built). it will be removed.  Adding "Slack" to the menu dropdown seems like the right place.

**Comment by diezguerra** [comment]
Adding Slack as direct link to open the Slack app, or to go to a view where only this box is shown?

**Comment by jcudmore** [comment]
@diezguerra sorry. it should be a direct link to slack. It can either open the app (if you have it downloaded) or open a new tab and go to www

**Comment by diezguerra** [comment]
Makes sense. And at that point the Slack module wouldn't show anywhere, correct?

So, to resolve this issue, the change should be simple given the new nav (ain't that right, @evanrs ?). As for the slack module code, we can get it out of sight and/or park it somewhere like ui, up to @evanrs and @ripleyaffect .

Not too happy that the module was so short lived, from a cost perspective..

**Comment by jcudmore** [comment]
@diezguerra i'm unhappy to see it go as well, but not sure where it lives yet. things are still evolving..
