### ISSUE TITLE
Provide link to FAQ in Nav overflow menu

### ISSUE THREAD

**Issue by darrellsilver** [Thinkful/ui#26]
From Darrell:
> Varun put together an amazing FAQ (https://settings.thinkful.com/support) but it should be linked from the Help nav in Eagle

**Comment by jcudmore** [comment]
@tholex FAQ is now live: https://www.thinkful.com/faq/

**Comment by darrellsilver** [comment]
@TatianaTylosky Can we change this name from "FAQ" to "Support"? That's the nav's name for it.

**Comment by varunrajan** [comment]
@TatianaTylosky @darrellsilver SGTM

**Comment by TatianaTylosky** [comment]
:+1:

**Comment by varunrajan** [comment]
@darrellsilver @jcudmore 

@TatianaTylosky has changed the URL to /support.
Can we move forward on linking this in the nav drop-down?

**Comment by darrellsilver** [comment]
:+1:

On Tue, Jun 2, 2015 at 3:20 PM, varunrajan <notifications@github.com> wrote:

> @darrellsilver <https://github.com/darrellsilver> @jcudmore
> <https://github.com/jcudmore>
>
> @TatianaTylosky <https://github.com/TatianaTylosky> has changed the URL
> to /support.
> Can we move forward on linking this in the nav drop-down?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/Thinkful/ui/issues/26#issuecomment-108064370>.
>



-- 
Darrell Silver
Co-founder of Thinkful

On Twitter: http://twitter.com/darrellsilver
At work: http://blog.thinkful.com/

**Comment by jcudmore** [comment]
Link in nav should say "Support"

**Comment by evanrs** [comment]
Closed by #57 and https://github.com/Thinkful/tfcommons/pull/147
