### ISSUE TITLE
Mentor reports dropdown has erratic behavior in Firefox and Safari

### ISSUE THREAD

**Issue by zellington** [Thinkful/ui#65]
As reported:
> combo boxes when going to enter student feedback

**Comment by learykara** [comment]
in which app was the mentor working @zellington ?

**Comment by diezguerra** [comment]
@zellington can we get more details on what the erratic behavior is and how to reproduce?

**Comment by diezguerra** [comment]
@zellington

**Comment by learykara** [comment]
Dropdowns and datepicker elements are the top of my priority list for cleanup cycle, fwiw

**Comment by learykara** [comment]
Fixed in https://github.com/Thinkful/ui/pull/132
