### ISSUE TITLE
Timezone component

### ISSUE THREAD

**Issue by varunrajan** [Thinkful/ui#78]
Do we have a finalized React component we can share across apps?

We have a pretty solid one here:
https://enroll.thinkful.com/signup/
![image](https://cloud.githubusercontent.com/assets/8453161/8166661/3a16db9a-1367-11e5-8ae6-7b86468dd112.png)

But it looks a little different and less responsive in the standard signup flow:
https://enroll.thinkful.com/enroll/availability
![image](https://cloud.githubusercontent.com/assets/8453161/8166671/42762656-1367-11e5-9dcc-e718fa532c8f.png)

**Comment by evanrs** [comment]
@varunrajan because the implementations use of jQuery this cannot be part of the UI library and will need to be in a separate repo/npm package.

cc @benjaminEwhite @rkuykendall
